### ISSUE TITLE
Icon buttons used in toolbar is not getting 'tabindex' value '0' when clicked

### ISSUE THREAD

**Issue by vivinkrishna-ni** [ni/nimble#1422] opened 2023-08-10 08:32 UTC
# 🐛 Bug Report

When using buttons with icons within the `nimble-toolbar` and clicking on the icon, the button does not receive a `tabindex=0`. By default, the first button in the toolbar possesses a `tabindex=0`, whereas the remaining buttons have a `tabindex=-1`. Consequently, upon pressing the `Tab` key to shift focus from the previously selected field to the buttons, the focus does not transition to the button that was most recently clicked.
 
## 💻 Repro or Code Sample

1. Add nimble buttons with an icon in it to a `nimble-toolbar`. 
2. Inspect the buttons and verify the default `tabindex` value.
3. Click the icon in the button which has `tabindex=-1`.
4. Notice the `tabindex` value in the dev tools.

## 🤔 Expected Behavior

The button which is clicked should be updated to `tabindex=0`. Also, the button which has `tabindex=0` previously should be updated to `tabindex=-1`.

## 😯 Current Behavior

The button which is clicked is not updated to `tabindex=0` when clicking on the icon. However, when clicking the button and not on the icon, the `tabindex=0`. However, upon clicking outside the icon, the `tabindex` gets updated.
![tabindex-issue-toolbar](https://github.com/ni/nimble/assets/123377523/c6b1469b-0bf4-45cc-91f5-74b44bb8f560)

## 💁 Possible Solution

Add `pointer-events: none;` to `start` or `end` slots where the icon is placed.

## 🔦 Context

In `nimble-rich-text-editor` component, for footer formatting options we use `nimble-toolbar` with the `nimble-toggle-button` just the icon enabled with it. For more details, see: https://github.com/ni/nimble/pull/1416#discussion_r1282725591 (issue 2)

~Currently, `nimble-rich-text-editor` has the workaround fix as mentioned in the possible solution, and here is the link to the PR: https://github.com/ni/nimble/pull/1503. Once the actual fix is implemented, the workaround in the editor styles should be removed.~

## 🌍 Your Environment

* OS & Device: Windows on PC
* Browser Google Chrome
* Version 115.0.5790.170

**Comment by mollykreis** [comment] 2023-08-14 18:16
I believe the issue is related to the `clickHandler` in FAST's toolbar. Within the `clickHandler`, the toolbar attempts to update its `activeIndex`, which represents which item in the toolbar should be focused. However, the check is that the item clicked is one of the focusable elements within the toolbar, not whether or not the item clicked is within one of the focusable elements. As a result, when the icon is clicked, the check doesn't pick up that the icon is within the focusable toolbar button, and the `activeIndex` doesn't get updated.

See: https://github.com/microsoft/fast/blob/218cfc014f5c76464493725f83bd883e8b07defa/packages/web-components/fast-foundation/src/toolbar/toolbar.ts#L134

**Comment by mollykreis** [comment] 2023-09-05 17:12
I created https://github.com/microsoft/fast/issues/6819 to track the underlying issue in the FAST toolbar.

However, we should also evaluate whether adding `pointer-events: none` to some of our nimble styles makes sense, such as the `start` and `end` slots of our button styles.

**Comment by jattasNI** [comment] 2023-10-05 17:02
Marking as blocked to reflect the dependency on the FAST issue.

**Closed** 2023-11-02 18:02 UTC
Labels: bug
