### ISSUE TITLE
Menu key in combobox does not open the browser native context menu

### ISSUE THREAD

**Issue by m-akinc** [ni/nimble#798] opened 2022-11-01 20:09 UTC
# 🐛 Bug Report

Pressing the context menu key on the keyboard when the combobox has focus should open the browser native context menu. It does nothing.

## 💻 Repro or Code Sample

Give the combobox focus and press the context menu button on the keyboard.

## 🤔 Expected Behavior

Context menu should open

## 😯 Current Behavior

Nothing happens

**Comment by rajsite** [comment] 2023-02-02 00:56
@m-akinc is there any context for where this requirement comes from? Aria keyboard interactions? FAST behavior? Native select control parity?

**Comment by atmgrifter00** [comment] 2023-02-06 16:19
So, for context, this issue seems to be present on Chrome and not Firefox. Additionally, this is happens with the [FAST Combobox](https://explore.fast.design/components/fast-combobox) as well. My feeling is that we should be filing an issue against FAST.

**Comment by rajsite** [comment] 2023-02-06 16:34
Ah I see. This issue is about the combobox blocking the browser native context menu when using the menu key: https://en.wikipedia.org/wiki/Menu_key

Right clicking to open the context menu and shift+f10 (didn't know that shortcut) to open the context menu aren't blocked. I was able to reproduce the issue using the context menu key of the windows on-screen keyboard.

I misunderstood and thought we were trying to open the combobox menu with that key. Instead we are trying to not accidentally block the native context menu from opening. Thanks for the context.

**Comment by fredvisser** [comment] 2024-02-02 16:42
Closing as low ROI

**Closed by fredvisser** 2024-02-02 16:42 UTC
Labels: bug, wontfix
