### ISSUE TITLE
Nimble Drawer is not correctly registering closing by pressing "esc" key.

### ISSUE THREAD

**Issue by SPathani-NI** [ni/nimble#1713] opened 2023-12-18 10:17 UTC
# 🐛 Bug Report

If "esc" is used to close nimble drawer, then then after closing the drawer will never reopen again with the following error in the console:
![image](https://github.com/ni/nimble/assets/147801131/5e763a9d-6ca6-4fac-b326-41b4feb51d24)

## 💻 Repro or Code Sample

can be replicated here : https://nimble.ni.dev/storybook/?path=/docs/components-drawer--docs

once open close the drawer by pressing esc then try opening it again.
## 🤔 Expected Behavior

Should properly register pressing esc as drawer closed.

## 😯 Current Behavior

https://github.com/ni/nimble/assets/147801131/87d97dc8-6ff8-4618-b69d-efcd3c225587

**Comment by mollykreis** [comment] 2024-01-02 15:20
This is a Chromium issue with the native `dialog` element that affects the latest versions of Edge and Chrome. The issue exists in the `nimble-drawer` and in the `nimble-dialog`.

From what I can tell, Chromium is working on getting the issue fixed soon. https://bugs.chromium.org/p/chromium/issues/detail?id=1512224

**Comment by rajsite** [comment] 2024-01-02 20:31
Discussion at standup:

- We will wait until next triage (1/9) to see if fixed in Chrome stable, if not we should consider a workaround
- The chromium issue suggests that user interaction requirement aligns with spec (spec requires user interaction to observe CloseWatcher events for security). So they may decide the behavior is not a bug in the future if the security requirement is necessary. We should make sure to have a regression test.

**Comment by saikrishnan-ni** [comment] 2024-01-08 13:58
Team,
We found a behavior with Chromium browsers for the drawer component and felt to be related to this issue, hence posting here.

When used in `Edge` browser, even with `preventDismiss` set pressing `Esc` registers and closes the drawer. 
This makes the drawer to not open again next time as it's state will mostly be dependent on any variable and whose state won't be updated.

i: This works as expected in chrome browser

**Comment by m-akinc** [comment] 2024-01-09 19:55
Issue is currently fixed in Chrome. Need to validate that the issue is fixed in the next Edge release (should be on Jan 25th). Releases: https://learn.microsoft.com/en-us/deployedge/microsoft-edge-release-schedule

**Comment by m-akinc** [comment] 2024-01-30 19:43
Validated in latest version of Edge and Chrome.

**Closed by m-akinc** 2024-01-30 19:43 UTC
Labels: bug
