### ISSUE TITLE
Cannot set breakpoints within storybook stories

### ISSUE THREAD

**Issue by mollykreis** [ni/nimble#2066] opened 2024-05-02 19:36 UTC
# 🧹 Tech Debt

After storybook was moved to its own package, you can no longer set breakpoints within the storybook files (e.g. `button.stories.ts`). Setting breakpoints within a component's source does work correctly while running storybook.

**Comment by m-akinc** [comment] 2024-05-02 21:42
I synced back to a commit from the end of February, and I still see the same behavior, i.e. `<component>.stories.ts` does not show up in debugger (only `<component>-tests-<component>-stories.iframe.bundle.js`) and attempting to put a breakpoint on the equivalent lines in the bundle file results in the message `Could not load content for webpack://ni/nimble-components/ (Fetch through target failed: Unsupported URL scheme; Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME)`.

Given that it wasn't a simple configuration problem introduced when moving to the new `storybook` package (or even necessarily a regression), I'm going to stop my investigation here.

**Comment by fredvisser** [comment] 2024-05-07 13:41
I assume these are related? – https://github.com/storybookjs/storybook/issues/26954 & https://github.com/storybookjs/storybook/issues/26653

**Comment by valentinpalkovic** [comment] 2024-05-22 08:31
@fredvisser Could you please try out the canary release of Storybook 0.0.0-pr-27171-sha-f81ba26a for testing purposes and let me know whether it fixes your issues related to source maps?

If you're using `@storybook/addon-coverage` please also update it to use the following canary release: `1.0.4--canary.42.041aa23.0`

**Comment by fredvisser** [comment] 2024-05-22 18:29
@valentinpalkovic - It looks like the Storybook canary release works well - thanks! 

(We aren't using `@storybook/addon-coverage`, so we didn't test that one).

**Comment by m-akinc** [comment] 2024-06-05 17:30
Storybook 8.2.0 should contain the fix. Check their [releases](https://github.com/storybookjs/storybook/releases) to see if it has been released yet.

**Comment by valentinpalkovic** [comment] 2024-07-08 10:36
The release of 8.2.0 is planned for this week!

**Closed** 2024-07-17 20:43 UTC
Labels: tech debt
