### ISSUE TITLE
Use of some nimble components is breaking Frontend V2.

### ISSUE THREAD

**Issue by SPathani-NI** [ni/nimble#1622] opened 2023-10-25 13:18 UTC
# 🐛 Bug Report

Use of certain nimble components such as select or combobox results in:
![image](https://github.com/ni/nimble/assets/147801131/e02d9847-9185-46ac-8dac-a68c3daad367)

I have not made any modifications to the examples given in nimble storybook.
In my observation this only occurs in components that share the same child component so for example select and combobox both use nimble-list-option similarly the error occurs while using menu button as menu and menu button share nimble-menu-item.
## 💻 Repro or Code Sample

repo: https://dev.azure.com/ni/DevCentral/_git/Tools?path=/report/dashboard/frontend_v2

the issue can be easily replicated by creating a sample test component and just directly using https://nimble.ni.dev/storybook/?path=/docs/components-select--docs in it.

## 🤔 Expected Behavior

the combobox or the component in question should render.

## 😯 Current Behavior

the component does not render on page at all with the "maximum call stack exceeded "error message provided earlier in browser console.

## 💁 Possible Solution

A solution that was working was turning the optimization off in options in angular.json and increasing the "maximumError" to 10 mb
![image](https://github.com/ni/nimble/assets/147801131/840e722c-1176-4cc2-af59-bc37cd9e4473)
![image](https://github.com/ni/nimble/assets/147801131/223b3817-5c2a-4466-92ba-5036b46544e2)

but we don't want to do it as it as it will lead to larger and slower bundle sizes.
## 🔦 Context

Because of it we are unable to use these nimble components at all.

## 🌍 Your Environment

relevant env details can be found in repo.

**Comment by atmgrifter00** [comment] 2023-10-25 14:04
@SPathani-NI, unfortunately, I don't think there is enough information in this issue for us to diagnose the problem. Is the repo you linked demonstrating the problem right now, or do you have to make changes in order to see it? What are the steps to actually reproduce the issue (even if you know how to reproduce it just using the Storybook examples in Nimble.

The issue you're reporting is curious in that we have several Angular applications right now successfully using the `Select` and `Combobox`. So, I'd like to see your actual usage of the `Select` or `Combobox` to see if there is any obvious distinction.

**Comment by rajsite** [comment] 2023-10-25 14:19
Are you on an old version of Nimble or Angular? The stack trace and behavior shown sound like a known issue in Angular's optimizer that FAST and Nimble have already worked around. I think the following issue describes the same behavior that has been resolved: https://github.com/microsoft/fast/issues/4793#issuecomment-895359635

**Comment by SPathani-NI** [comment] 2023-10-25 14:27
No the current repo does not have the issue as these components are not used there.
To exactly recreate the issue:
-make a local branch from the repo.
-goto src\app\systems\initiators\initiators.component.html
- add the nimble select as given in the storybook: https://nimble.ni.dev/storybook/?path=/docs/components-select--docs
anywhere in the code.
-compile and reload the page in your local dev env.

**Comment by SPathani-NI** [comment] 2023-10-25 14:30
current versions:
{
  "name": "frontend-v2",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test --no-watch --no-progress",
    "lint": "ng lint",
    "lint:fix": "ng lint --fix"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^14.2.0",
    "@angular/cdk": "~13.3.9",
    "@angular/common": "^14.2.0",
    "@angular/compiler": "^14.2.0",
    "@angular/core": "^14.2.0",
    "@angular/forms": "^14.2.0",
    "@angular/material": "~13.3.9",
    "@angular/platform-browser": "^14.2.0",
    "@angular/platform-browser-dynamic": "^14.2.0",
    "@angular/router": "^14.2.0",
    "@ni/nimble-angular": "^16.6.9",
    "ngx-infinite-scroll": "^14.0.0",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^14.2.9",
    "@angular/cli": "~14.2.9",
    "@angular/compiler-cli": "^14.2.0",
    "@ni/eslint-config-angular": "^5.0.4",
    "@types/jasmine": "~4.0.0",
    "autoprefixer": "^10.4.13",
    "jasmine-core": "~4.3.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "source-map-loader": "^4.0.1",
    "typescript": "~4.7.2"
  }
}

**Comment by SPathani-NI** [comment] 2023-10-25 14:41
Also regarding updating nimble
So if I update my nimble by changing "@ni/nimble-angular": "^16.6.9" to "@ni/nimble-angular":"^17.7.1" and deleting the package-lock file and do "npm install" 
The whole frontend V2 is breaking with nothing rendering at all 
with the same "Uncaught RangeError: Maximum call stack size exceeded" in console

**Comment by rajsite** [comment] 2023-10-25 15:42
@SPathani-NI there are dozens of Angular applications shipping with Nimble components such as under [Skyline Web/Workspaces](https://dev.azure.com/ni/DevCentral/_git/Skyline?path=/Web/Workspaces/) (some specific examples from that directory include [TestInsights](https://dev.azure.com/ni/DevCentral/_git/Skyline?path=/Web/Workspaces/TestInsights)). 

Unfortunately, nothing is immediately coming to mind from what you have shared so far. I'd ask for you to try and narrow down what difference in settings or configuration in your application is causing issues compared to the applications in Skyline Web or from the angular workspace configuration in Nimble.

**Comment by rajsite** [comment] 2023-10-25 15:48
Some things to look out for:
- make sure you are integrating nimble as discussed in the steps in the README: https://github.com/ni/nimble/tree/main/angular-workspace/projects/ni/nimble-angular#getting-started
- Notably take care on step 2 which emphasizes that you need to import the module associated with every component used.

If you are having difficulty narrowing down the issue you can try providing an example branch that reproduces the issue.

**Comment by atmgrifter00** [comment] 2023-10-26 15:10
When I build your repo and launch the app I get these errors:
![image](https://github.com/ni/nimble/assets/26874831/e7953570-0702-4424-b05e-65f2ba47d351)

![image](https://github.com/ni/nimble/assets/26874831/7976f663-e1b7-4c04-a99b-fad2642ec0c2)

Is there some other step I'm missing?

**Comment by aluqmanj** [comment] 2023-10-27 06:35
@atmgrifter00 You can follow the steps [here](https://dev.azure.com/ni/DevCentral/_git/Tools?path=/deploy/infrastructure/dashboard/docker/README.md&version=GBmain&_a=preview&anchor=steps%3A) to setup a dev Dashboard environment. This requires docker, Artifactory credentials and a git clone of the [Tools repo](https://dev.azure.com/ni/DevCentral/_git/Tools?version=GBmain).

**Comment by SPathani-NI** [comment] 2023-11-02 12:53
@atmgrifter00 This is still not working for me.
I think a better way to isolate the bug is by creating a new component and using combobox in that.

can u do "ng g c test --module app" in terminal
then in app-routing-module add " { path: 'system-logs', title: 'Logs | Systems', component: TestComponent },"

then try using components in that.

**Comment by rajsite** [comment] 2023-11-02 12:59
@SPathani-NI instead of giving instructions like that can you create a minimal,  self contained reproducing example?  You can create a new example in https://dev.azure.com/ni/Users f for example

**Comment by SPathani-NI** [comment] 2023-11-15 12:42
@rajsite I tried to replicate the bug in [stackblitz](https://stackblitz.com/edit/create-a-basic-angular-component-qdnktr?file=package.json), I kept all the dependencies the same and here the nimble components are working fine.

So, I don't think an external reproducible example would work.

**Comment by rajsite** [comment] 2023-11-15 12:50
@SPathani-NI unfortunately we don't have the bandwidth to reproduce your dev environment locally to try and help root cause the issue. We strongly encourage finding a way to make a standalone example that reproduce the issue.

**Comment by jattasNI** [comment] 2023-11-20 14:57
[Internal SO post](https://ni.stackenterprise.co/questions/15186/15203#15203) suggesting this is most likely an issue with trying to build with support for older browsers in `.browserslist.rc`.

**Comment by aluqmanj** [comment] 2023-11-21 06:38
This issue was resolved by lowering our browser support from the last 20 versions to the last 7 versions ([PR](https://dev.azure.com/ni/DevCentral/_git/Tools/pullrequest/601988?_a=files&path=/report/dashboard/frontend_v2/.browserslistrc)). 

It would be helpful if there was some kind of recommended browser support in Nimble's documentation for future reference.

**Comment by jattasNI** [comment] 2023-11-21 14:33
I filed #1680 to track this. Since you figured out the problem I'll close out this issue.

**Closed by jattasNI** 2023-11-21 14:33 UTC
Labels: bug, waiting for response, internal-app
