### ISSUE TITLE
Error text size is too small

### ISSUE THREAD

**Issue by m-akinc** [ni/nimble#768] opened 2022-09-29 19:17 UTC
# 🐛 Bug Report

Error text size is currently 9, but is hard to read. It should be bumped up to 11.

**Comment by NIbokeefe** [comment] 2022-10-06 21:31
I have completed updating the tokens in the Nimble_Components DSP document to reflect the new typography changes for errors on controls; 11px Source Sans Pro.

I have also gone through each individual control for each UI theme and updated the error typography to use the correct tokens and adjusted the container height to 14px.

**Comment by nate-ni** [comment] 2022-10-13 14:28
Duplicate of/Addressed with #775

**Closed by nate-ni** 2022-10-13 14:28 UTC
Labels: bug, UX
