### ISSUE TITLE
SystemLinkShared `editGridIconHtml` property is not redered in development

### ISSUE THREAD

**Issue by gergo-papp** [ni/nimble#1173] opened 2023-04-10 14:43 UTC
# 🐛 Bug Report

## 💻 Repro or Code Sample

Thi sis how the edit grid icon is currently built:
```typescript
import { DesignSystem } from '@microsoft/fast-foundation';
import { IconThreeVerticalLines } from '@ni/nimble-components/dist/esm/icons/three-vertical-lines';

export class SLGridColumns {
    public static readonly editGridIconHtml = `<${DesignSystem.tagFor(IconThreeVerticalLines)}></${DesignSystem.tagFor(IconThreeVerticalLines)}>`;
}
```

Then this gets evaluated in development, while running with a linked configuration, the `DesignSystem.tagFor(IconThreeVerticalLines)` evaluates to `undefined`

## 🤔 Expected Behavior

It should work in dev

## 😯 Current Behavior

```
SLGridColumns.editGridIconHtml === undefined;
```

## 💁 Possible Solution

As a quick fix, we can hardcode the tag

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by jattasNI** [comment] 2023-04-10 15:12
@mollykreis could you take a look at this as part of your SLE grid refactoring?

One thing to try would be to use [iconThreeVerticalLinesTagName](https://github.com/ni/nimble/blob/adae0d3ab801c7c87acf53cc48025d855465fd5c/packages/nimble-components/build/generate-icons/source/index.js#L42) instead of `DesignSystem.tagFor()`. This is the long term preferred approach but we haven't gotten to #1094 yet to do this holistically.

**Comment by rajsite** [comment] 2023-04-10 16:39
> One thing to try would be to use [iconThreeVerticalLinesTag](https://github.com/ni/nimble/blob/adae0d3ab801c7c87acf53cc48025d855465fd5c/packages/nimble-components/build/generate-icons/source/index.js#L42) instead of `DesignSystem.tagFor()`. This is the long term preferred approach but we haven't gotten to #1094 yet to do this holistically.

Which you can see that the `<iconName>Tag` export is [created by invoking `DesignSystem.tagFor`](https://github.com/ni/nimble/blob/adae0d3ab801c7c87acf53cc48025d855465fd5c/packages/nimble-components/build/generate-icons/source/index.js#L65). So I would be surprised if that resolved to different things as the underlying implementation is the same,

> Then this gets evaluated in development, while running with a linked configuration, the DesignSystem.tagFor(IconThreeVerticalLines) evaluates to undefined

@gergo-papp the behavior you see is only in development configuration not production right? Can you give more details of the development configuration you are using?

I [tried to reproduce the issue](https://github.com/ni/nimble/compare/deve-mode-icon-tag-name?expand=1) using an angular dev config build in the example app but did not run into the same behavior.

**Comment by rajsite** [comment] 2023-04-12 23:58
Root cause was a multi-workspace repository attempting to [link multiple workspaces together using tsconfig paths](https://stackoverflow.com/questions/59356732/angular-library-and-live-reload/71375807#71375807) resulting in resolved import paths for the same identifier unpredictably pulling from `node_modules` folders in different workspaces.

This resulted in the import of `fast-foundation` resolving to multiple modules each creating registries resulting in multiple instances of what should be singleton objects. The specific approach used for linking across workspaces is not valid for modules relying on standard npm node module resolution such as nimble.

Discussion to improve the behavior of the multi-workspace repo is in [Skyline](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullrequest/469740).

**Closed by rajsite** 2023-04-12 23:58 UTC
Labels: bug
