### ISSUE TITLE
IconSeverity has no effect in a disabled button

### ISSUE THREAD

**Issue by searly** [ni/nimble#1824] opened 2024-02-14 16:46 UTC
# 🐛 Bug Report

The icon of a disabled button is always gray.

## 💻 Repro or Code Sample

    <NimbleButton Disabled="true">
        <NimbleIconPlay slot="start" Severity="IconSeverity.Success"/>
    </NimbleButton>

## 🤔 Expected Behavior

Icon should keep the severity color but  have dimmed opacity.

## 😯 Current Behavior

![image](https://github.com/ni/nimble/assets/5291443/1c0cb0e8-921a-4f9b-9189-b9a12c69220a)

## 💁 Possible Solution

Current workaround is to reset the --ni-nimble-icon-color token.

## 🌍 Your Environment

nimble blazor

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by jattasNI** [comment] 2024-02-19 19:41
Our visual designer @NIbokeefe hinted that his preference might be that disabled button icons shouldn't be colored since we might not want to draw that much attention to disabled items. Brandon is going to reach out to James to discuss.

**Comment by m-akinc** [comment] 2024-02-27 20:47
@NIbokeefe any update on this? Do we actually want disabled icons to have some color?

**Comment by fredvisser** [comment] 2024-03-01 16:39
Closing as "working as designed"

**Closed by fredvisser** 2024-03-01 16:39 UTC
Labels: bug, team review
